### PR TITLE
[ecosystem CI] Add automatic retry on agent loss and agent shutdown

### PR DESCRIPTION
**Pull request by architkulkarni**
Closes https://github.com/ray-project/kuberay/issues/1382

### CODE REVIEW

**Comment by architkulkarni** [comment]
Not sure the best way to test this before merging.

**Comment by aslonnie** [comment]
> Not sure the best way to test this before merging.

you can always add unit tests. the ray civ1 one is here:

https://buildkite.com/ray-project/rayci/builds/399#018a4d7e-426d-40fc-bd62-8e86d3366cb7

also, you can manually launch a kuberay pipeline run, and add a env var of `PIPELINE_REPO_BRANCH=architkulkarni-patch-1` , which will load from this branch rather from master.

this is the logic in the buildkite init steps, and it is why `PIPELINE_REPO_BRANCH` is specially handled:

```
      - export PIPELINE_REPO_DIR=\$(mktemp -d)
      - git clone https://github.com/ray-project/rayci "\$PIPELINE_REPO_DIR"
      - pushd "\$PIPELINE_REPO_DIR" || true
      - '[ -n "\$PIPELINE_REPO_BRANCH" ] && git fetch origin "\$PIPELINE_REPO_BRANCH" && git checkout origin/"\$PIPELINE_REPO_BRANCH"'
      - popd || true
      - python3 -m pip install -Ur "\$PIPELINE_REPO_DIR/ecosystem_ci/requirements.txt"
      - python3 "\$PIPELINE_REPO_DIR/ecosystem_ci/build_pipeline.py" '.buildkite/*.yml' | buildkite-agent pipeline upload
      - rm -rf "\$PIPELINE_REPO_DIR"
```

**Comment by aslonnie** [comment]
or just yolo it in.. and fix things after it is broken.. might be fine if the traffic is low..

**Comment by architkulkarni** [comment]
@aslonnie Thanks for the tip!! I'm testing it with the env var approach, and it got past the pipeline build step: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/1507#018a4db8-7576-4f5d-b62e-4147560f51e8/131-141

So I'm comfortable with merging this PR at this point

**Review by aslonnie — APPROVED** [review]

**Comment by aslonnie** [comment]
merging for you.

**Pull request merged**
