### PR TITLE
upgrade v1 base building script to use wanda v0.1.3

### PR DESCRIPTION
**Pull request by aslonnie**
add `-name_prefix` and `-work_repo` flag

### CODE REVIEW

**Comment by aslonnie** [comment]
test build: https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/398#018a0169-923a-41a5-90bf-b2c686236189

**Comment by aslonnie** [comment]
build fails.. needs to release and upgrade to v0.1.2 now..

**Comment by aslonnie** [comment]
trying again: https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/400

**Comment by aslonnie** [comment]
with v0.1.3

**Comment by aslonnie** [comment]
working https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/400#018a0245-0714-4104-82c0-4ca65848eb18  :)

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
