### PR TITLE
[ci] automatic retries for general errors

### PR DESCRIPTION
**Pull request by can-anyscale**
Enable automatic retries for general errors (wheel, docker, java, etc.). We changed test failure exit code to 42 in https://github.com/ray-project/ray/pull/41174 so this won't hide flaky tests.

Test:
- CI

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/marvelstudios/">Marvel Studios</a> on <a href="https://giphy.com/gifs/marvelstudios-3ohhweiVB36rAlqVCE">GIPHY</a></div>

**Comment by aslonnie** [comment]
maybe add `BUILDKITE_RETRY_COUNT` into the buildkite env var list, and add a test job that exits with 1 if `BUILDKITE_RETRY_COUNT` is 0 or not set?

**Comment by aslonnie** [comment]
> maybe add `BUILDKITE_RETRY_COUNT` into the buildkite env var list, and add a test job that exits with 1 if `BUILDKITE_RETRY_COUNT` is 0 or not set?

or do it as a follow up

**Comment by can-anyscale** [comment]
added BUILDKITE_RETRY_COUNT and a retry test job

**Pull request merged**
